"""Runtime configuration for Airlock.

Everything works with zero configuration: the pipeline runs fully offline with a
local generator, real measured fitness, and a local deployer. Set the env vars
below to promote any stage to a real provider — nothing else changes.

    AIRLOCK_LLM_BASE   OpenAI-compatible chat endpoint (e.g. a Nosana-hosted
    AIRLOCK_LLM_KEY    open model, or api.openai.com/v1). When set, variants are
    AIRLOCK_LLM_MODEL  generated by the model instead of the local synthesizer.

    DAYTONA_API_KEY    When set, each variant is built and served inside a real
    DAYTONA_API_URL    Daytona sandbox instead of the local renderer.

    DNSIMPLE_TOKEN     When set, the chosen champion is published to a real
    DNSIMPLE_ACCOUNT   subdomain via the DNSimple API.
    DNSIMPLE_DOMAIN
"""
import os
from dataclasses import dataclass, field


def _load_dotenv():
    """Load KEY=VALUE lines from a gitignored `.env` at the project root, without
    overriding anything already exported. Lets you keep a real DAYTONA_API_KEY on
    disk (never in the shell history, never printed) so the SDK can read it."""
    path = os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env")
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))
    except OSError:
        pass


_load_dotenv()


def _int(name, default):
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


@dataclass
class Config:
    # pipeline shape — the funnel is a schedule, not a constant (see README)
    n_generate: int = field(default_factory=lambda: _int("AIRLOCK_N", 40))
    k_finalists: int = field(default_factory=lambda: _int("AIRLOCK_K", 5))
    generations: int = field(default_factory=lambda: _int("AIRLOCK_GENERATIONS", 5))
    elite_count: int = field(default_factory=lambda: _int("AIRLOCK_ELITES", 6))
    defect_rate: float = field(default_factory=lambda: float(os.environ.get("AIRLOCK_DEFECT_RATE", 0.42)))
    # demo choreography: pace the fan-out and the between-generation beat so a
    # viewer can actually watch fitness climb. 0 = as fast as possible (real runs).
    pace_ms: int = field(default_factory=lambda: _int("AIRLOCK_PACE_MS", 12))
    gen_pace_ms: int = field(default_factory=lambda: _int("AIRLOCK_GEN_PACE_MS", 0))

    # optional real providers (empty => offline/local implementation)
    llm_base: str = field(default_factory=lambda: os.environ.get("AIRLOCK_LLM_BASE", ""))
    llm_key: str = field(default_factory=lambda: os.environ.get("AIRLOCK_LLM_KEY", ""))
    llm_model: str = field(default_factory=lambda: os.environ.get("AIRLOCK_LLM_MODEL", "gpt-4o-mini"))

    daytona_key: str = field(default_factory=lambda: os.environ.get("DAYTONA_API_KEY", ""))
    daytona_url: str = field(default_factory=lambda: os.environ.get(
        "DAYTONA_API_URL", "https://app.daytona.io/api"))

    dnsimple_token: str = field(default_factory=lambda: os.environ.get("DNSIMPLE_TOKEN", ""))
    dnsimple_account: str = field(default_factory=lambda: os.environ.get("DNSIMPLE_ACCOUNT", ""))
    dnsimple_domain: str = field(default_factory=lambda: os.environ.get("DNSIMPLE_DOMAIN", ""))

    host: str = field(default_factory=lambda: os.environ.get("AIRLOCK_HOST", "127.0.0.1"))
    port: int = field(default_factory=lambda: _int("AIRLOCK_PORT", 8770))

    # where variant/champion artifacts are written
    work_dir: str = field(default_factory=lambda: os.environ.get(
        "AIRLOCK_WORK", os.path.join(os.path.dirname(os.path.dirname(__file__)), "runs")))

    def provider_labels(self):
        from .llm import _provider_label
        return {
            "llm": _provider_label(self.llm_base) if self.llm_base else "templates",
            "sandbox": "Daytona" if self.daytona_key else "local-render",
            "deploy": "DNSimple" if self.dnsimple_token else "local",
        }
